/**
 * Dota 2 catalog depth. The heroes here are the twenty the filter sidebar
 * already offers (`facets.mock.HEROES`), so picking one returns real rows
 * instead of an empty grid.
 */
import { fromDota, type CatalogSeedItem, type DotaTuple } from "./catalog.types";

/** `[hero, name, slug, rarity, slot, priceUsd]` */
const ROWS: DotaTuple[] = [
  ["Phantom Assassin", "Crimson Wake", "crimson-wake", "immortal", "Back", 62.4],
  ["Phantom Assassin", "Blades of Voth Domosh", "blades-voth-domosh", "rare", "Weapon", 18.75],
  ["Invoker", "Dark Artistry Bracers", "dark-artistry-bracers", "immortal", "Armor", 44.9],
  ["Invoker", "Magus Apex", "magus-apex", "arcana", "Head", 289.0],
  ["Invoker", "Sunstrike Signet", "sunstrike-signet", "mythical", "Weapon", 12.3],
  ["Pudge", "Feast of Abscession", "feast-of-abscession", "arcana", "Weapon", 412.5],
  ["Pudge", "Butcher's Apron", "butchers-apron", "rare", "Back", 9.85],
  ["Pudge", "Toll of the Blighted Marsh", "toll-blighted-marsh", "mythical", "Head", 21.4],
  ["Juggernaut", "Sanguine Mask", "sanguine-mask", "rare", "Head", 16.2],
  ["Juggernaut", "Bladeform Fury", "bladeform-fury", "immortal", "Weapon", 78.0],
  ["Juggernaut", "Arms of the Onyx Crucible", "arms-onyx-crucible", "mythical", "Armor", 27.6],
  ["Anti-Mage", "Wanderer's Silhouette", "wanderers-silhouette", "immortal", "Back", 55.3],
  ["Anti-Mage", "Blades of the Wayfarer", "blades-wayfarer", "rare", "Weapon", 14.4],
  ["Anti-Mage", "Antediluvian Visage", "antediluvian-visage", "mythical", "Head", 23.9],
  ["Shadow Fiend", "Demon Eater", "demon-eater", "arcana", "Head", 348.0],
  ["Shadow Fiend", "Fires of Nether Reach", "fires-nether-reach", "immortal", "Weapon", 96.5],
  ["Shadow Fiend", "Soul Harvester Pauldrons", "soul-harvester-pauldrons", "mythical", "Armor", 19.8],
  ["Crystal Maiden", "Frost Avalanche", "frost-avalanche", "arcana", "Head", 267.4],
  ["Crystal Maiden", "Crystalline Comet", "crystalline-comet", "immortal", "Weapon", 71.2],
  ["Crystal Maiden", "Glacial Mantle", "glacial-mantle", "rare", "Back", 11.5],
  ["Faceless Void", "Claszureme Incursion", "claszureme-incursion", "immortal", "Weapon", 128.9],
  ["Faceless Void", "Timelost Visor", "timelost-visor", "mythical", "Head", 24.7],
  ["Faceless Void", "Chronoshard Wrap", "chronoshard-wrap", "rare", "Armor", 8.4],
  ["Lina", "Blaze Armor of the Conflagration", "blaze-armor-conflagration", "arcana", "Armor", 301.0],
  ["Lina", "Ember Crown", "ember-crown", "immortal", "Head", 64.8],
  ["Lina", "Searing Scepter", "searing-scepter", "mythical", "Weapon", 17.9],
  ["Legion Commander", "Blades of the Duelist", "blades-duelist", "immortal", "Weapon", 88.6],
  ["Legion Commander", "Ascendant Warhelm", "ascendant-warhelm", "rare", "Head", 13.2],
  ["Legion Commander", "Banner of the Fifth Legion", "banner-fifth-legion", "mythical", "Back", 29.5],
  ["Terrorblade", "Fractured Visage", "fractured-visage", "arcana", "Head", 322.5],
  ["Terrorblade", "Demon Marauder Blades", "demon-marauder-blades", "immortal", "Weapon", 107.3],
  ["Terrorblade", "Sundered Wings", "sundered-wings", "mythical", "Back", 33.1],
  ["Queen of Pain", "Eminence of Ristul", "eminence-of-ristul", "arcana", "Head", 276.9],
  ["Queen of Pain", "Scourge of Nothl", "scourge-of-nothl", "immortal", "Weapon", 59.7],
  ["Queen of Pain", "Whip of Torment", "whip-of-torment", "rare", "Weapon", 10.6],
  ["Spectre", "Shadowforce Cuirass", "shadowforce-cuirass", "immortal", "Armor", 83.4],
  ["Spectre", "Dagger of the Dissolute", "dagger-dissolute", "mythical", "Weapon", 26.2],
  ["Spectre", "Veil of the Haunted", "veil-of-the-haunted", "rare", "Back", 7.9],
  ["Sniper", "Trapper's Scattergun", "trappers-scattergun", "immortal", "Weapon", 68.1],
  ["Sniper", "Bushmaster's Cap", "bushmasters-cap", "rare", "Head", 6.75],
  ["Sniper", "Marksman's Bandolier", "marksmans-bandolier", "mythical", "Armor", 15.8],
  ["Windranger", "Fervor of the Gale", "fervor-of-the-gale", "immortal", "Weapon", 74.6],
  ["Windranger", "Windrunner's Cowl", "windrunners-cowl", "mythical", "Head", 20.3],
  ["Windranger", "Zephyr Cloak", "zephyr-cloak", "rare", "Back", 9.2],
  ["Tinker", "Reworked Rocket Rig", "reworked-rocket-rig", "immortal", "Back", 51.9],
  ["Tinker", "Adaptive Optics Visor", "adaptive-optics-visor", "mythical", "Head", 18.4],
  ["Tinker", "Tinkbot Companion", "tinkbot-companion", "rare", "Couriers", 4.85],
  ["Rubick", "Grand Magus Regalia", "grand-magus-regalia", "arcana", "Armor", 258.0],
  ["Rubick", "Stolen Scepter", "stolen-scepter", "immortal", "Weapon", 66.3],
  ["Rubick", "Arcanist's Turban", "arcanists-turban", "mythical", "Head", 22.1],
  ["Storm Spirit", "Tempest Helm of the Thundergod", "tempest-helm-thundergod", "immortal", "Head", 142.7],
  ["Storm Spirit", "Voltaic Coils", "voltaic-coils", "mythical", "Armor", 25.4],
  ["Storm Spirit", "Stormcaller's Sash", "stormcallers-sash", "rare", "Back", 8.1],
  ["Earthshaker", "Totem of the Thundergod", "totem-of-the-thundergod", "immortal", "Weapon", 91.8],
  ["Earthshaker", "Bedrock Pauldrons", "bedrock-pauldrons", "mythical", "Armor", 16.7],
  ["Earthshaker", "Seismic Mask", "seismic-mask", "rare", "Head", 5.95],
  ["Axe", "Helm of the Mad Axe", "helm-of-the-mad-axe", "immortal", "Head", 57.2],
  ["Axe", "Bloodchaser Cleaver", "bloodchaser-cleaver", "mythical", "Weapon", 23.3],
  ["Axe", "Red Mist Cape", "red-mist-cape", "rare", "Back", 7.4],
  ["Pudge", "Hook, Line and Sinker", "hook-line-sinker", "rare", "Taunts", 12.9],
  ["Axe", "Axe's Chop Shop", "axes-chop-shop", "rare", "Taunts", 11.2],
  ["Invoker", "Quas Wex Exort Flourish", "qwe-flourish", "mythical", "Taunts", 19.6],
  ["Crystal Maiden", "Frostbite Courier", "frostbite-courier", "mythical", "Couriers", 31.8],
  ["Terrorblade", "Reflection Drake", "reflection-drake", "rare", "Couriers", 9.45],
];

export const DOTA_ITEMS: CatalogSeedItem[] = ROWS.map(fromDota);
