import { Icon } from "@/components/ui/icon";
import type { VerifyMobile } from "../../data/verify-mobile.mock";

/** Sentinel ribbon and the challenge hero (pill, shield mark, title, account). */
export function ShieldHero({ data }: { data: VerifyMobile }) {
  return (
    <>
      <div className="flex items-center justify-between bg-surface-container-lowest px-space-md py-space-xs">
        <div className="flex items-center gap-space-xs">
          <span className="h-2 w-2 animate-ping rounded-full bg-status-live" />
          <span className="font-label-badge text-label-badge tracking-widest text-text-primary uppercase">STEAM 2FA SENTINEL</span>
        </div>
        <div className="flex items-center gap-space-sm text-text-secondary">
          <span className="flex items-center gap-1 font-data-mono-md text-data-mono-md">
            <Icon name="bolt" className="text-[13px] text-tertiary" /> {data.latency}
          </span>
          <span className="flex items-center gap-1 font-data-mono-md text-data-mono-md text-primary">
            <Icon name="sync" className="text-[13px]" /> SECURE
          </span>
        </div>
      </div>

      <div className="relative flex flex-col items-center overflow-hidden px-space-md pt-space-lg pb-space-md text-center">
        <div className="pointer-events-none absolute -top-12 h-56 w-56 rounded-full bg-primary/10 blur-3xl" />
        <div className="pointer-events-none absolute top-2 h-32 w-32 rounded-full bg-glow-crimson blur-2xl" />
        <div className="mb-space-md inline-flex items-center gap-1.5 rounded-full bg-primary/15 px-space-sm py-0.5 text-primary shadow-xs">
          <Icon name="shield_locked" className="text-[14px]" />
          <span className="font-label-badge text-label-badge font-semibold tracking-wider uppercase">ESCROW CHALLENGE ACTIVE</span>
        </div>
        <div className="relative mb-space-sm flex h-24 w-24 items-center justify-center">
          <div className="absolute inset-0 animate-pulse rounded-2xl bg-linear-to-tr/srgb from-primary-container via-status-live to-tertiary opacity-25 blur-md" />
          <div className="relative flex h-20 w-20 items-center justify-center rounded-xl bg-surface-container-high shadow-xl">
            <svg className="h-12 w-12 text-primary" fill="none" stroke="currentColor" strokeWidth="1.75" viewBox="0 0 24 24" aria-hidden>
              <path className="fill-[rgb(244_63_94/0.12)]" d="M12 2L4 5v6.09c0 5.05 3.41 9.76 8 10.91 4.59-1.15 8-5.86 8-10.91V5l-8-3z" />
              <path
                fill="currentColor"
                d="M12 11a2.5 2.5 0 0 0-2.5 2.5c0 1.03.62 1.9 1.5 2.28V17a1 1 0 0 0 2 0v-1.22c.88-.38 1.5-1.25 1.5-2.28A2.5 2.5 0 0 0 12 11z"
              />
              <circle cx="12" cy="7.5" fill="none" r="1.5" stroke="currentColor" strokeWidth="1.5" />
            </svg>
            <span className="absolute -right-1 -bottom-1 flex h-6 w-6 items-center justify-center rounded-full bg-tertiary text-[13px] font-bold text-on-tertiary shadow-md">
              <Icon name="key" className="text-[14px]" />
            </span>
          </div>
        </div>
        <h2 className="mb-space-xs font-headline-lg-mobile text-headline-lg-mobile font-semibold text-text-primary">Steam Guard Mobile 2FA</h2>
        <p className="max-w-xs font-body-sm text-body-sm leading-relaxed text-text-secondary">
          Enter the 5-character authorization code generated by your Steam Mobile Authenticator for account{" "}
          <span className="rounded bg-surface-container px-1.5 py-0.5 font-data-mono-md text-[12px] font-semibold text-text-primary">{data.handle}</span>
        </p>
      </div>
    </>
  );
}
