import {
  Activity,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUpRight,
  AtSign,
  Award,
  Backpack,
  BadgeCheck,
  Banknote,
  Bell,
  BellPlus,
  BellRing,
  Bitcoin,
  Bomb,
  BookOpen,
  Bot,
  Calendar,
  ChartColumn,
  ChartLine,
  ChartNoAxesCombined,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleCheck,
  CircleCheckBig,
  CircleDollarSign,
  CirclePlay,
  CirclePlus,
  CircleQuestionMark,
  CircleUser,
  CircleX,
  ClipboardPaste,
  Clock,
  Coins,
  Compass,
  Contrast,
  Copy,
  CreditCard,
  Dices,
  Download,
  Droplets,
  ExternalLink,
  Eye,
  EyeOff,
  FileDown,
  FingerprintPattern,
  Flame,
  Funnel,
  Gamepad2,
  Gauge,
  Gavel,
  Gem,
  Globe,
  Grid3x3,
  Headset,
  Heart,
  HeartHandshake,
  HeartPulse,
  Hourglass,
  Info,
  Key,
  KeyRound,
  Landmark,
  LayoutGrid,
  List,
  ListChecks,
  ListFilter,
  ListPlus,
  LoaderCircle,
  LocateFixed,
  Lock,
  LockKeyhole,
  LockOpen,
  LogIn,
  LogOut,
  Mail,
  MailCheck,
  Maximize,
  Medal,
  MemoryStick,
  Menu,
  MessageCircle,
  MessageSquare,
  MessagesSquare,
  Mic,
  MicVocal,
  MonitorPlay,
  Moon,
  MoveRight,
  Package,
  Palette,
  Pencil,
  Percent,
  Pin,
  Play,
  Plus,
  Pointer,
  QrCode,
  Radar,
  Radio,
  RadioTower,
  Receipt,
  RefreshCw,
  Repeat,
  Rotate3d,
  RotateCcwClock,
  Router,
  Rows3,
  Satellite,
  Search,
  SearchX,
  Send,
  SendHorizontal,
  Server,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  SlidersHorizontal,
  Smartphone,
  Snowflake,
  Sparkle,
  Sparkles,
  Star,
  StarHalf,
  Store,
  Sun,
  Swords,
  Tag,
  Target,
  Terminal,
  Ticket,
  Timer,
  TimerOff,
  Trash,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Trophy,
  Tv,
  Upload,
  User,
  UserPlus,
  Users,
  Video,
  Wallet,
  WandSparkles,
  Workflow,
  X,
  Zap,
} from "lucide-react";
import type { ComponentType, SVGProps } from "react";
import type { IconName } from "./icon-names";

export const ICON_MAP: Record<IconName, ComponentType<SVGProps<SVGSVGElement>>> = {
  "3d_rotation": Rotate3d,
  ac_unit: Snowflake,
  account_balance: Landmark,
  account_balance_wallet: Wallet,
  account_circle: CircleUser,
  account_tree: Workflow,
  add: Plus,
  add_circle: CirclePlus,
  add_shopping_cart: ShoppingCart,
  add_task: ListPlus,
  alternate_email: AtSign,
  analytics: ChartNoAxesCombined,
  apps: Grid3x3,
  arrow_back: ArrowLeft,
  arrow_back_ios_new: ChevronLeft,
  arrow_drop_down: ChevronDown,
  arrow_drop_up: ChevronUp,
  arrow_forward: ArrowRight,
  arrow_outward: ArrowUpRight,
  auto_awesome: Sparkles,
  auto_fix_high: WandSparkles,
  backpack: Backpack,
  badge: BadgeCheck,
  bar_chart: ChartColumn,
  blur_on: Droplets,
  bolt: Zap,
  bomb: Bomb,
  cancel: CircleX,
  casino: Dices,
  cell_tower: RadioTower,
  chat: MessageCircle,
  check: Check,
  check_circle: CircleCheck,
  checklist: ListChecks,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  close: X,
  confirmation_number: Ticket,
  content_copy: Copy,
  content_paste: ClipboardPaste,
  contrast: Contrast,
  credit_card: CreditCard,
  currency_bitcoin: Bitcoin,
  currency_exchange: ArrowLeftRight,
  dark_mode: Moon,
  delete_sweep: Trash,
  diamond: Gem,
  dns: Server,
  done: Check,
  download: Download,
  edit: Pencil,
  electric_bolt: Zap,
  equalizer: SlidersHorizontal,
  error: CircleAlert,
  event: Calendar,
  expand_more: ChevronDown,
  explore_off: Compass,
  favorite: Heart,
  file_download: FileDown,
  filter_alt: Funnel,
  filter_list: ListFilter,
  finance_mode: TrendingUp,
  fingerprint: FingerprintPattern,
  flare: Sparkle,
  flash_on: Zap,
  forum: MessagesSquare,
  fullscreen: Maximize,
  gavel: Gavel,
  gps_fixed: LocateFixed,
  grid_view: LayoutGrid,
  groups: Users,
  gshield: ShieldCheck,
  help: CircleQuestionMark,
  help_center: CircleQuestionMark,
  history: RotateCcwClock,
  hotel_class: Star,
  hourglass_top: Hourglass,
  hub: Share2,
  info: Info,
  insights: ChartLine,
  inventory_2: Package,
  key: Key,
  light_mode: Sun,
  live_tv: Tv,
  local_fire_department: Flame,
  lock: Lock,
  lock_clock: Lock,
  lock_open: LockOpen,
  lock_reset: LockKeyhole,
  login: LogIn,
  logout: LogOut,
  magic_button: WandSparkles,
  mail: Mail,
  mark_email_read: MailCheck,
  memory: MemoryStick,
  menu: Menu,
  menu_book: BookOpen,
  mic: Mic,
  military_tech: Medal,
  monetization_on: CircleDollarSign,
  monitor_heart: HeartPulse,
  monitoring: Activity,
  north_east: ArrowUpRight,
  notification_add: BellPlus,
  notifications: Bell,
  notifications_active: BellRing,
  open_in_new: ExternalLink,
  palette: Palette,
  passkey: KeyRound,
  payments: Banknote,
  percent: Percent,
  person: User,
  person_add: UserPlus,
  phonelink_lock: Smartphone,
  phonelink_ring: Smartphone,
  pin: Pin,
  play_arrow: Play,
  play_circle: CirclePlay,
  policy: ShieldCheck,
  progress_activity: LoaderCircle,
  public: Globe,
  publish: Upload,
  pulse_alert: Activity,
  qr_code_2: QrCode,
  query_stats: ChartLine,
  radar: Radar,
  receipt_long: Receipt,
  record_voice_over: MicVocal,
  refresh: RefreshCw,
  report_problem: TriangleAlert,
  router: Router,
  satellite_alt: Satellite,
  schedule: Clock,
  search: Search,
  search_off: SearchX,
  security: Shield,
  security_update_good: ShieldCheck,
  sell: Tag,
  send: Send,
  send_to_mobile: SendHorizontal,
  sensors: Radio,
  settings: Settings,
  share: Share2,
  shield: Shield,
  shield_lock: Shield,
  shield_locked: ShieldCheck,
  shield_person: Shield,
  shield_with_heart: HeartHandshake,
  shopping_bag: ShoppingBag,
  smart_display: MonitorPlay,
  smart_toy: Bot,
  smartphone: Smartphone,
  sms: MessageSquare,
  speed: Gauge,
  sports_esports: Gamepad2,
  sports_kabaddi: Users,
  star: Star,
  star_half: StarHalf,
  stars: Sparkles,
  storefront: Store,
  support_agent: Headset,
  swap_horiz: ArrowLeftRight,
  swap_horizontal_circle: ArrowLeftRight,
  switch_account: Repeat,
  swords: Swords,
  sync: RefreshCw,
  sync_alt: RefreshCw,
  tag: Tag,
  target: Target,
  task_alt: CircleCheckBig,
  terminal: Terminal,
  timelapse: Timer,
  timer: Timer,
  timer_off: TimerOff,
  token: Coins,
  toll: Coins,
  touch_app: Pointer,
  trending_down: TrendingDown,
  trending_flat: MoveRight,
  trending_up: TrendingUp,
  trophy: Trophy,
  tune: SlidersHorizontal,
  verified: BadgeCheck,
  verified_user: ShieldCheck,
  videocam: Video,
  view_agenda: Rows3,
  view_list: List,
  visibility: Eye,
  visibility_off: EyeOff,
  vpn_key: KeyRound,
  warning: TriangleAlert,
  waterfall_chart: ChartColumn,
  whatshot: Flame,
  workspace_premium: Award,
};
