"use client";

import Image from "next/image";
import { NoticeButton } from "@/components/notice-button";
import { Icon } from "@/components/ui/icon";
import { cn } from "@/lib/cn";
import { formatMoney } from "@/lib/format";
import type { CheckoutItem } from "../types";

export function CheckoutItems({ items, onRemove }: { items: CheckoutItem[]; onRemove: (id: string) => void }) {
  return <section className="flex flex-col gap-space-sm"><div className="flex flex-col justify-between gap-space-xs px-1 sm:flex-row sm:items-center"><div className="flex items-center gap-space-sm"><h2 className="font-headline-sm text-headline-sm font-bold text-text-primary uppercase">Allocated Reserve Items</h2><span className="rounded-full bg-primary-container px-2 py-0.5 font-label-badge text-label-badge font-bold text-on-primary-container">{items.length} Items Held</span></div><div className="flex items-center gap-1 font-label-badge text-label-badge text-text-muted uppercase"><Icon name="timer" className="text-[15px] text-tertiary" />Cart Vault Reservation: <span className="font-data-mono-md text-tertiary"><span className="sr-only">14 minutes </span><CountdownLabel /></span></div></div>{items.map((item) => <CheckoutItemRow key={item.id} item={item} onRemove={() => onRemove(item.id)} />)}</section>;
}

function CountdownLabel() {
  return <span>14:38</span>;
}

function CheckoutItemRow({ item, onRemove }: { item: CheckoutItem; onRemove: () => void }) {
  return <article className="flex flex-col justify-between gap-space-md rounded-xl bg-surface-card p-space-md shadow-md md:flex-row md:items-center"><div className="flex min-w-0 items-start gap-space-md sm:items-center"><div className="relative flex h-20 w-20 shrink-0 items-center justify-center overflow-hidden rounded-lg bg-surface-container-lowest sm:h-24 sm:w-24"><Image src={item.image} alt={item.imageAlt} fill sizes="96px" className="object-cover" /><span className={cn("absolute top-1 left-1 rounded px-1.5 py-0.5 font-label-badge text-[9px] font-bold uppercase", item.badgeTone)}>{item.badge}</span><span className={cn("absolute right-1 bottom-1 rounded bg-surface-dim/90 px-1.5 py-0.5 font-label-badge text-[9px]", item.markerTone)}>{item.marker}</span></div><div className="flex min-w-0 flex-col gap-1"><div className="flex flex-wrap items-center gap-2"><span className={cn("rounded bg-surface-container-high px-1.5 py-0.5 font-label-badge text-[10px] font-semibold uppercase", item.gameTone)}>{item.game}</span><span className="truncate font-body-lg text-body-lg font-bold text-text-primary">{item.name}</span></div><span className="font-body-sm text-body-sm text-text-secondary">{item.detail}</span><div className="flex flex-wrap items-center gap-2 font-data-mono-md text-label-badge text-text-muted"><span className="flex items-center gap-1 text-tertiary"><Icon name="military_tech" className="text-[13px]" />{item.intel[0]}</span><span>•</span><span>{item.intel[1]}</span><span>•</span><span className="rounded bg-surface-container-lowest px-1.5 py-0.5 text-status-upcoming">{item.bot}</span></div></div></div><div className="flex shrink-0 items-center justify-between gap-space-md md:flex-col md:items-end md:justify-center"><div className="flex flex-col md:items-end"><span className="font-data-mono-lg text-data-mono-lg font-bold text-text-primary">{formatMoney(item.price)}</span><span className="flex items-center gap-1 font-label-badge text-label-badge text-status-upcoming uppercase"><span className="h-1.5 w-1.5 rounded-full bg-status-upcoming" />Instant 0s Bot Push</span></div><div className="flex items-center gap-2"><NoticeButton notice={{ title: `${item.name} saved`, description: "Wishlist sync is available when the account API is connected." }} aria-label={`Save ${item.name} to wishlist`} className="h-auto rounded p-1.5 text-text-muted hover:bg-surface-container-high hover:text-text-primary"><Icon name="favorite" className="text-[18px]" /></NoticeButton><NoticeButton notice={{ title: `${item.name} removed`, description: "Cart updates are simulated until the checkout API is connected." }} onClickCapture={onRemove} aria-label={`Remove ${item.name}`} className="h-auto rounded p-1.5 text-text-muted hover:bg-error-container/20 hover:text-error"><Icon name="close" className="text-[18px]" /></NoticeButton></div></div></article>;
}
