"use client";

import { useMemo, useState } from "react";
import { NoticeButton } from "@/components/notice-button";
import { Icon } from "@/components/ui/icon";
import { Input } from "@/components/ui/input";
import { Select, type SelectOption } from "@/components/ui/select";
import type { WalletTransaction } from "../types";

const TYPE_OPTIONS: readonly SelectOption<string>[] = ["All Transactions", "Deposits Only", "Withdrawals Only", "Marketplace Sales", "Marketplace Purchases"].map((label) => ({ value: label, label }));
const RANGE_OPTIONS: readonly SelectOption<string>[] = ["Last 30 Days", "This Quarter", "Year to Date", "All-Time Archive"].map((label) => ({ value: label, label }));
const STATUS = { live: "text-tertiary", cyan: "text-status-upcoming", amber: "text-tertiary" } as const;

export function WalletAuditLedger({ transactions }: { transactions: WalletTransaction[] }) {
  const [query, setQuery] = useState("");
  const [type, setType] = useState("All Transactions");
  const [range, setRange] = useState("Last 30 Days");
  const visible = useMemo(() => transactions.filter((transaction) => `${transaction.title} ${transaction.hash} ${transaction.asset} ${transaction.node}`.toLowerCase().includes(query.toLowerCase())), [transactions, query]);
  return (
    <section className="flex flex-col gap-space-md rounded-xl bg-surface-card p-space-lg shadow-xl">
      <div className="flex flex-col justify-between gap-space-md xl:flex-row xl:items-center"><div className="flex items-center gap-space-sm"><div className="flex h-8 w-8 items-center justify-center rounded-lg bg-surface-container-high text-text-primary"><Icon name="receipt_long" className="text-[20px]" /></div><div><h3 className="font-headline-sm text-headline-sm text-text-primary">Cryptographic Treasury Audit Ledger</h3><p className="font-body-sm text-body-sm text-text-secondary">Immutable log of peer-to-peer escrow transactions and fiat settlements.</p></div></div><div className="flex flex-wrap items-center gap-space-xs">{[["TOTAL DEPOSITED:", "$14,290.00", "text-tertiary"], ["TOTAL CASHED OUT:", "$9,850.00", "text-primary"], ["NET PROFIT / SURPLUS:", "+$4,440.00", "text-status-upcoming"]].map(([label, value, tone]) => <div key={label} className="flex items-center gap-space-xs rounded-lg bg-surface-container-lowest px-space-md py-1.5"><span className="font-label-badge text-[10px] text-text-muted">{label}</span><span className={`font-data-mono-md text-body-sm font-bold ${tone}`}>{value}</span></div>)}</div></div>
      <div className="flex flex-col items-stretch justify-between gap-space-sm rounded-xl bg-surface-container-lowest p-space-sm md:flex-row md:items-center"><div className="flex flex-1 items-center gap-space-xs rounded-lg bg-surface-card px-space-sm py-1.5"><Icon name="search" className="text-[18px] text-text-muted" /><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search by Tx Hash, Item Name, Steam Trade ID, or Counterparty..." aria-label="Search treasury transactions" className="h-auto border-0 bg-transparent p-0 font-body-sm text-body-sm text-text-primary focus-visible:ring-0" /></div><div className="flex flex-wrap items-center gap-space-xs"><Select label="Filter transactions" value={type} onValueChange={setType} options={TYPE_OPTIONS} triggerClassName="cursor-pointer rounded-lg bg-surface-card px-space-sm py-2 pr-7 font-label-caps text-[11px] text-text-secondary uppercase" iconClassName="absolute top-2.5 right-2 text-[16px] text-text-muted" /><Select label="Filter date range" value={range} onValueChange={setRange} options={RANGE_OPTIONS} triggerClassName="cursor-pointer rounded-lg bg-surface-card px-space-sm py-2 pr-7 font-label-caps text-[11px] text-text-secondary uppercase" iconClassName="absolute top-2.5 right-2 text-[16px] text-text-muted" /><NoticeButton notice={{ title: "Audit export queued", description: "CSV and tax reports download once the wallet API is wired." }} className="h-auto gap-1 rounded-lg border-0 bg-surface-container-high px-space-md py-2 font-label-caps text-[11px] text-text-primary uppercase hover:bg-surface-container-highest"><Icon name="file_download" className="text-[16px]" /><span>CSV / Tax Audit</span></NoticeButton></div></div>
      <div className="overflow-x-auto"><table className="w-full min-w-225 border-collapse text-left font-body-sm"><thead><tr className="bg-surface-container-lowest font-label-caps text-[11px] text-text-muted uppercase"><th className="rounded-l-lg px-space-md py-3">Transaction &amp; Hash</th><th className="px-space-md py-3">Asset Details / Counterparty</th><th className="px-space-md py-3">Execution Node</th><th className="px-space-md py-3">Amount (USD)</th><th className="px-space-md py-3">Audited Status</th><th className="rounded-r-lg px-space-md py-3 text-right">Proof / Action</th></tr></thead><tbody>{visible.map((transaction) => <tr key={transaction.id} className="transition-colors hover:bg-surface-container-high/30"><td className="px-space-md py-3.5"><div className="flex items-center gap-space-xs"><div className="flex h-7 w-7 items-center justify-center rounded-lg bg-surface-container-high text-tertiary"><Icon name={transaction.icon} className="text-[16px]" /></div><div className="flex flex-col"><span className="font-headline-sm text-[13px] font-semibold text-text-primary">{transaction.title}</span><span className="font-data-mono-md text-[11px] text-text-muted">{transaction.hash}</span></div></div></td><td className="px-space-md py-3.5"><div className="flex flex-col"><span className="text-text-primary">{transaction.asset}</span><span className="font-data-mono-md text-[11px] text-text-muted">{transaction.detail}</span></div></td><td className="px-space-md py-3.5 font-data-mono-md text-[11px] text-status-upcoming">{transaction.node}</td><td className={`px-space-md py-3.5 font-data-mono-md text-data-mono-md font-bold ${transaction.amountTone === "primary" ? "text-primary" : "text-tertiary"}`}>{transaction.amount}</td><td className="px-space-md py-3.5"><span className={`inline-flex items-center gap-1 rounded bg-surface-container-lowest px-2 py-0.5 font-label-badge text-[10px] ${STATUS[transaction.statusTone]}`}><span className="h-1.5 w-1.5 rounded-full bg-status-live" />{transaction.status}</span></td><td className="px-space-md py-3.5 text-right"><NoticeButton notice={{ title: transaction.action, description: "Proof details are available when the treasury API is connected." }} className="inline-flex h-auto gap-0.5 rounded-none border-0 p-0 font-label-caps text-[11px] text-text-secondary uppercase hover:text-text-primary"><span>{transaction.action}</span><Icon name={transaction.actionIcon} className="text-[14px]" /></NoticeButton></td></tr>)}</tbody></table></div>
      <div className="flex flex-col items-center justify-between gap-space-sm pt-space-xs sm:flex-row"><span className="font-data-mono-md text-body-sm text-text-muted">Showing records 1 - {visible.length} of 148 verified entries</span><div className="flex items-center gap-space-xs"><NoticeButton notice={{ title: "First page", description: "You are already viewing the first audit page." }} disabled className="h-auto rounded-lg border-0 bg-surface-container-lowest px-space-md py-1.5 font-label-caps text-[11px] text-text-muted uppercase" />{[1, 2, 3].map((page) => <NoticeButton key={page} notice={{ title: `Audit page ${page}`, description: "Paging loads additional records once the wallet API is wired." }} className={`h-auto rounded-lg border-0 px-space-md py-1.5 font-data-mono-md text-[12px] ${page === 1 ? "bg-primary-container text-on-primary-container" : "bg-surface-container-lowest text-text-secondary"}`}>{page}</NoticeButton>)}<NoticeButton notice={{ title: "Next page", description: "Paging loads additional records once the wallet API is wired." }} className="h-auto rounded-lg border-0 bg-surface-container-lowest px-space-md py-1.5 font-label-caps text-[11px] text-text-secondary uppercase" /></div></div>
    </section>
  );
}
